### PR TITLE
Proposed msgs for Cartesian Impedance

### PR DESCRIPTION
**Pull request by rkojcev**
This is set of proposed msgs for setting Cartesian Impedance parameters. Currently tested on KUKA iiwa R800

### CODE REVIEW

**Comment by rkojcev** [comment]
from @davetcoleman

> Thoughts on majorana msgs:
> 
> Is it possible to have fewer message? e.g. reuse existing messages instead of creating multiple custom ones for a i.e. 2x3 matrix (CartesianDamping) or a message that just wraps a Twist (MaxCartesianVelocity)?
> Are you planning on polling the greater ROS community to find people with experience with impedance control to get their feedback? I haven't worked on this recently, or much, so do not have the best feedback for standard message types

**Comment by rkojcev** [comment]
> Is it possible to have fewer message? e.g. reuse existing messages instead of creating multiple custom ones for a i.e. 2x3 matrix (CartesianDamping) or a message that just wraps a Twist (MaxCartesianVelocity)?

Yes indeed but we need to discuss this. We had some previous discussion manly between @shaun-edwards  and @gavanderhoorn in my previous [pull request](https://github.com/ros-industrial-consortium/majorana/pull/1)

I can envision putting common msgs like for example the damping into a matrix, but on the other side we have to be careful due to the fact that the units for the the impedance can be different for translation and rotation. For example, for the Cartesian stiffness, the units for the translation are in [N/m] and for the rotation are in [Nm/rad]. The damping is a case where for now, is represented as Lehr's ratios.

> Are you planning on polling the greater ROS community to find people with experience with impedance control to get their feedback? I haven't worked on this recently, or much, so do not have the best feedback for standard message types

I would really like to have as much as feedback as possible. I have written couple of emails before both to the ROS mailing list and ROS-I mailing list. Hope I would get interest from the wider community and get some feedback. I hope that with mutual efforts from the community we can try to standardize set of messages for Cartesian Impedance and Force Control.

**Comment by rkojcev** [comment]
@shaun-edwards, @gavanderhoorn  should we create two packages. One for the Cartesian Impedance msgs and one for the Force Control msgs? or keep them in one package?

**Comment by rkojcev** [comment]
@shaun-edwards, @gavanderhoorn should we merge this?

**Comment by shaun-edwards** [comment]
Let's merge (+1) this since GSoC is ending and we need to checkpoint your progress for that.  There is probably more discussion to have as things evolve or get merged into the common message set.

**Comment by rkojcev** [comment]
I agree with you @shaun-edwards. Merging and closing.

**Pull request merged**
